"""empty message

Revision ID: 2031c32c63b7
Revises: e7714f51fc9d
Create Date: 2017-10-09 16:23:48.176140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2031c32c63b7'
down_revision = 'e7714f51fc9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shoppinglists', sa.Column('share_staus', sa.Boolean(), nullable=True))
    op.add_column('shoppinglists', sa.Column('shared_by', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shoppinglists', 'shared_by')
    op.drop_column('shoppinglists', 'share_staus')
    # ### end Alembic commands ###
