"""empty message

Revision ID: 4ebadc51d3d7
Revises: 2f005d5c36a6
Create Date: 2017-09-14 22:25:29.891002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ebadc51d3d7'
down_revision = '2f005d5c36a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shoppinglists', 'stuff')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shoppinglists', sa.Column('stuff', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
