"""empty message

Revision ID: a866d0667a98
Revises: 4ebadc51d3d7
Create Date: 2017-09-16 21:40:51.719123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a866d0667a98'
down_revision = '4ebadc51d3d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('joined_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'joined_on')
    # ### end Alembic commands ###
