"""empty message

Revision ID: e86d2dceb3e5
Revises: a866d0667a98
Create Date: 2017-09-26 11:55:14.689299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e86d2dceb3e5'
down_revision = 'a866d0667a98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shoppingitems', sa.Column('bought', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shoppingitems', 'bought')
    # ### end Alembic commands ###
